---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_zero

# Let's make it a policy that we'll keep no more than
# 3 major revs of a given platform. That should fall
# close to, or better than, the version support provided by
# the distribution (ex. remove Centos 5 when Centos 8 is added)
platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.0
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: fedora-19
  - name: fedora-20
  - name: fedora-21
  - name: debian-6.0.9
  - name: debian-7.4
  - name: debian-8.0

suites:
  - name: default
    run_list:
      - recipe[ulimit2::default]
    attributes:
      ulimit:
        params:
          default:
            nofile: 10240
            nproc:
              soft: 2048
          root:
            nofile:
              soft: 15360
              hard: 'unlimited'
          '@sysadmin':
            nproc:
              hard: 4096
